// --------- MÉTODOS DE EMPLEADOS -----------------------------------------------------
###
GET http://localhost:3000/empleados HTTP/1.1

###
POST http://localhost:3000/empleados/insertar_empleado/ HTTP/1.1
Content-Type: application/json

{
    "PV_emp_nom_empleado": "David Hernandez",
    "PI_emp_id_empleado": 22640,
    "PV_emp_email_empleado": "dh@unah.hn",
    "PC_emp_estado_civil": "s",
    "PI_emp_cod_estatus": 1,
    "PI_emp_cod_cargo": 1,
    "PI_emp_tipo_contrato": 1,
    "PV_emp_usr_adicion": "Angela",
    "PV_emp_usr_modificacion": "Sayra"
    
}

###
GET http://localhost:3000/empleados/obtener_empleado/8 HTTP/1.1

###
PUT http://localhost:3000/empleados/actualizar_empleado/8 HTTP/1.1
Content-Type: application/json

{
    
    "emp_nom_empleado": "David Terstegen",
    "emp_id_empleado": "22640",
    "emp_email_empleado": "davidmatute@yahoo.com",
    "emp_estado_civil": "s",
    "emp_cod_estatus": "1",
    "emp_cod_cargo": "1",
    "emp_tipo_contrato": "1",
    "emp_usr_adicion": "Angela",
    "emp_usr_modificacion": "Sayra"
    
}

###
DELETE http://localhost:3000/empleados/eliminar_empleado/8 HTTP/1.1

// --------- MÉTODOS DE USUARIOS ------------------------------------------------------
###
GET http://localhost:3000/usuarios HTTP/1.1

###
POST http://localhost:3000/usuarios/insertar_usuario/ HTTP/1.1
Content-Type: application/json

{
    "PV_usr_cod_usuario": "4",
    "PV_usr_password": "futbol24",
    "PV_usr_nom_usuario": "Daniela",
    "PI_usr_cod_estatus": 2,
    "PV_usr_loguead": "s",
    "PI_usr_cod_tipo_usuario": 1,
    "PV_usr_usr_adicion": "sss",
    "PV_usr_usr_modificacion": "Gabriela"
}
 
###
GET http://localhost:3000/usuarios/usuario/4 HTTP/1.1

###
PUT http://localhost:3000/usuarios/actualizar_usuario/4 HTTP/1.1
Content-Type: application/json

{
    "usr_password": "password22",
    "usr_nom_usuario": "Dennisse Valladares",
    "usr_cod_empleado": 2,
    "usr_cod_estatus": 2,
    "usr_loguead": "s",
    "usr_cod_tipo_usuario": 1,
    "usr_usr_adicion": "sSs",
    "usr_usr_modificacion": "David Matute"
}

###
DELETE http://localhost:3000/usuarios/eliminar_usuario/34 HTTP/1.1


// --------- MÉTODOS DE PROVEEDORES -----------------------------------------------------
###
GET http://localhost:3000/proveedores HTTP/1.1

###
POST http://localhost:3000/proveedores/insertar_proveedor/ HTTP/1.1
Content-Type: application/json

{
    "PV_prv_nom_proveedor": "Ingrid Molina",
    "PI_prv_id_proveedor": 23215487,
    "PV_prv_email_proveedor": "JHH@yahoo.com",
    "PI_cod_estatus": 1,
    "PI_prv_cod_pais": 1,
    "PV_prv_usr_adicion": "David Matute",
    "PV_prv_usr_modificacion": "FFF",
    "PV_prv_direccion_proveedor": 1,
    "PI_prv_telefono_proveedores" : 21212121,
    "PV_des_direccion_proveedor" : "El Carrizal",
    "PI_num_telefono_proveedor" : 21212121,
    "PV_nom_contacto": "IngridM" 

}


###
GET http://localhost:3000/proveedores/obtener_proveedor/2 HTTP/1.1

###
PUT http://localhost:3000/proveedores/actualizar_proveedor/2 HTTP/1.1
Content-Type: application/json

{
    
    "prv_nom_proveedor": "David Matute",
    "prv_id_proveedor": 2,
    "prv_email_proveedor": "davidmatute@unah.com",
    "prv_cod_estatus": 66,
    "prv_cod_pais": 66,
    "prv_usr_adicion": "FFF",
    "prv_usr_modificacion": "FFF",
    "prv_direccion_proveedores": 2342,
    "prv_telefono_proveedores": 23233434
}

###
DELETE http://localhost:3000/proveedores/eliminar_proveedor/13 HTTP/1.1

// --------- MÉTODOS DE CLIENTES -----------------------------------------------------

###
GET http://localhost:3000/clientes HTTP/1.1

###
POST http://localhost:3000/clientes/insertar_cliente/ HTTP/1.1
Content-Type: application/json

{
    "cli_cod_cliente": "",
    "PV_cli_nom_cliente": "Dory",
    "PV_cli_cod_tipo_persona": 1,
    "PI_cli_id_rtn": 0801199946372,
    "PI_cli_id_cliente": 111,
    "PI_cli_cod_estatus": 1,
    "PV_cli_email_cliente": "buscoYsemeolvida@pixar.com",
    "PV_cli_cod_pais": 1,
    "PV_cli_usr_adicion": "David Matute",
    "PV_cli_usr_modificacion": "DM",
    "PV_des_tipo_persona": "memoria a corto plazo"
}

###
GET http://localhost:3000/clientes/obtener_cliente/9 HTTP/1.1

###
PUT http://localhost:3000/clientes/actualizar_cliente/2 HTTP/1.1
Content-Type: application/json


{
    
    "PV_cli_nom_cliente": "David",
    "PV_cli_cod_tipo_persona": 4,
    "PI_cli_id_rtn": 80767,
    "PI_cli_id_cliente": 43498,
    "PI_cli_cod_estatus": 1,
    "PV_cli_email_cliente": "david@unah.hn",
    "PV_cli_cod_pais": 1,
    "PV_cli_usr_adicion": "Yo",
    "PV_cli_usr_modificacion": "ju"   
}

###
DELETE http://localhost:3000/clientes/eliminar_cliente/2 HTTP/1.1

// --------- MÉTODOS DE CARGAS A ENVIAR -----------------------------------------------------

###
GET http://localhost:3000/cargas_enviar HTTP/1.1

###
POST http://localhost:3000/cargas_enviar/insertar_cargas_enviar/ HTTP/1.1
Content-Type: application/json

{
    "PD_Kg_Carga_Enviar": 12.5,
    "PV_des_Carga_Enviar": "Churros Yummis",
    "PI_can_Carga_Enviar": 12,    
    "PI_cod_Carga_Futura": 2,
    "PI_cod_Carga_Entregada": 6,
    "PV_cenv_usr_adicion": "David Matute",
    "PV_cenv_usr_modifico": "Theo Rosales"
}

###
GET http://localhost:3000/cargas_enviar/obtener_carga_enviar/5 HTTP/1.1

###
PUT http://localhost:3000/cargas_enviar/actualizar_carga_enviar/5 HTTP/1.1
Content-Type: application/json

{
    //"PI_cod_Carga_Enviar": 5,
    "PD_Kg_Carga_Enviar": 2.9,
    "PV_des_Carga_Enviar": "Boca Deli",
    "PI_can_Carga_Enviar": 8,
    "PI_cod_Carga_Futura": 2,
    "PI_cod_Carga_Entregada": 6,
    "PV_cenv_usr_adicion": "Darwin Valladares",
    "PV_cenv_usr_modifico": "David Matute"
}

###
DELETE http://localhost:3000/cargas_enviar/eliminar_carga_enviar/1 HTTP/1.1

// --------- MÉTODOS DE CARGAS ENTREGADAS ---------------------------------------------------

###
GET http://localhost:3000/carga_ent HTTP/1.1

###
POST http://localhost:3000/carga_ent/insertar_carga_ent/ HTTP/1.1
Content-Type: application/json

{
    "PI_cod_Carga_Enviar": 5,
    "PV_des_Carga_Entregada": "",
    "PV_cent_usr_adicion": "Sarutobi sensei",
    "PV_cent_usr_modifico": "David"
}

###
GET http://localhost:3000/carga_ent/obtener_carga_ent/5 HTTP/1.1

###
PUT http://localhost:3000/carga_ent/actualizar_carga_ent/7 HTTP/1.1
Content-Type: application/json

{
    "PI_cod_Carga_Enviar": 5,
    "PV_des_Carga_Entregada": "La Costeña",
    "PV_cent_usr_adicion": "Dayana",
    "PV_cent_usr_modifico": "David"
}

###
DELETE http://localhost:3000/carga_ent/eliminar_carga_ent/6 HTTP/1.1

// --------- MÉTODOS DE CARGOS -----------------------------------------------

###

GET http://localhost:3000/cargos HTTP/1.1

###
POST http://localhost:3000/cargos/insertar_cargo/ HTTP/1.1
Content-Type: application/json

{
    "PI_cod_cargo": 6,
    "PV_des_cargo": "Gerente"
}

###
GET http://localhost:3000/cargos/obtener_cargo/1 HTTP/1.1

###
PUT http://localhost:3000/cargos/actualizar_cargo/1 HTTP/1.1
Content-Type: application/json

{
    "PI_cod_cargo": 1,
    "PV_des_cargo": "Administrador"
}

###
DELETE http://localhost:3000/cargos/eliminar_cargo/6 HTTP/1.1

// --------- MÉTODOS DE ESTADOS -----------------------------------------------

###
GET http://localhost:3000/estados HTTP/1.1

###
POST http://localhost:3000/estados/insertar_estado/ HTTP/1.1
Content-Type: application/json

{
    "PI_cod_estatus": 8,
    "PV_des_estatus": "Gee"
}

###
GET http://localhost:3000/estados/obtener_estado/2 HTTP/1.1

###
PUT http://localhost:3000/estados/actualizar_estado/2 HTTP/1.1
Content-Type: application/json

{
    "PI_cod_estatus": 2,
    "PV_des_estatus": "Activo"
}

###
DELETE http://localhost:3000/estados/eliminar_estado/5 HTTP/1.1

// --------- MÉTODOS DE PAISES ---------------------------------------------------

###
GET http://localhost:3000/pais HTTP/1.1

###
POST http://localhost:3000/pais/insertar_pais/ HTTP/1.1
Content-Type: application/json

{
    "PI_cod_pais": 2,
    "PV_nom_pais": "Brasil",
    "PV_abr_pais": "BE"
}

###
GET http://localhost:3000/pais/obtener_pais/2 HTTP/1.1

###
PUT http://localhost:3000/pais/actualizar_pais/2 HTTP/1.1
Content-Type: application/json

{
    "PI_cod_pais": 2,
    "PV_nom_pais": "Venezuela",
    "PV_abr_pais": "VE"
}

###
DELETE http://localhost:3000/pais/eliminar_pais/7 HTTP/1.1

// --------- MÉTODOS DE TIPO DE CONTRATOS -----------------------------------------------

###
GET http://localhost:3000/tipo_contrato HTTP/1.1

###
POST http://localhost:3000/tipo_contrato/insertar_tipo_contrato/ HTTP/1.1
Content-Type: application/json

{
    "PI_cod_tipo_contrato": 3,
    "PV_des_tipo_contrato": "Gee"
}

###
GET http://localhost:3000/tipo_contrato/obtener_tipo_contrato/2 HTTP/1.1

###
PUT http://localhost:3000/tipo_contrato/actualizar_tipo_contrato/1 HTTP/1.1
Content-Type: application/json

{
    "PI_cod_tipo_contrato": 1,
    "PV_des_tipo_contrato": "Tiempo Completo"
}

// --------- MÉTODOS PARA LA AUTORIZACIÓN DEL TOKEN ----------------------------

###
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJub21icmUiOiJEYXZpZCIsImVtYWlsIjoibWF0dXRlQHVuYWguaG4ifSwiaWF0IjoxNjU4Nzk1Mjc1fQ.lH7iPcSFRzwMOnmZnTdqjsXrdIDE0o-pKoEt-8hwYJA